# Generated by Django 5.1.1 on 2024-10-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
    ]
